In [ ]:
#Write a program to print a dictionary where the keys are numbers between 1 & 15 (both inclusive) and the values are square of keys.

d = {}

for i in range(1, 16):
  d[i] = i**2

print("The final dictionary is: ", d)

The final dictionary is:  {1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121, 12: 144, 13: 169, 14: 196, 15: 225}

In [3]:
#2. Write a program to store 5 roll no and their names in key value format. Search for roll no input by user and display the corresponding name

d = {}

for i in range(5):
  d[i] = int(input("Enter your roll: "))

rolnum = int(input("Enter the roll number: "))
print (d)
print("The corresponding name with the roll number is: ", d[rolnum - 1])

Enter your roll: 4
Enter your roll: 3
Enter your roll: 2
Enter your roll: 1
Enter your roll: 8
Enter the roll number: 2
{0: 4, 1: 3, 2: 2, 3: 1, 4: 8}
The corresponding name with the roll number is:  3

In [2]:
32#3. Write a program to store 10 country and their capitals in a key value format. Display name of countries whose capital name starts with letter ‘A’

d = eval(input("Enter the country and then the capital for each pair: "))

print("The dictionary is: ", d)

for country in d:
  if d[country]

SyntaxError: ignored

In [ ]:
class Student:

    #class variable
    count=0

    #constuctor
    def __init__(self):
        #instance variable
        self.stud_id= 0 
        self.stud_name=""
        self.stud_marks=0
    """
    #constuctor
    def __init__(self,id,name,marks):
        #instance variable
        self.stud_id=id
        self.stud_name=name
        self.stud_marks=marks
        """

    def input_data(self):
        self.stud_id=int(input("Enter a id:"))
        self.stud_name=input("Enter a Name:")
        self.stud_marks=int(input("Enter a id:"))


  
    def calculate_grade(self):
        #local variable
        grade=''
        if(self.stud_marks >=90):
            grade='A'
        elif(self.stud_marks >80 and self.stud_marks <90 ):
            grade='B'
        else:
            grade='C'
        print("Grade:",grade)

    def display(self):
        print("Id:",self.stud_id)
        print("Name:",self.stud_name)
        print("Marks:",self.stud_marks)
        
s1=Student()
s1.display()
"""
s2=Student(2,'Akshu',99)
s1.input_data()
s1.calculate_grade()
s1.display()
"""

Id: 0
Name:
Marks: 0

"\ns2=Student(2,'Akshu',99)\ns1.input_data()\ns1.calculate_grade()\ns1.display()\n"

In [ ]:
class Employee:

  def __init__(self):
    self.userid = 0
    self.username = ""
    self.usersalary = 0

  def input_data(self):
    self.userid = int(input("Enter your userid: "))
    self.username = input("Enter your name: ")
    self.usersalary = int(input("Enter your salary: "))

  def gross_salary(self):
    if self.usersalary <= 20000:
      grossalary = self.usersalary - (20*self.usersalary/100) - (7*self.usersalary/100) - (8.33*self.usersalary/100)
    elif self.usersalary <= 50000 and self.usersalary > 20000:
       grossalary = self.usersalary - (30*self.usersalary/100) - (10*self.usersalary/100) - (8.33*self.usersalary/100)
    else:
      grossalary = self.usersalary - (35*self.usersalary/100) - (12*self.usersalary/100) - (8.33*self.usersalary/100)
    
    print("The gross salary of the Employee: ", grossalary)

  def display(self):
      print("Your id is: ", self.userid)
      print("Your name is: ", self.username)
      print("Your usersalary is: ", self.usersalary)

emp1 = Employee()
emp1.input_data()
emp1.gross_salary()
emp1.display()

Enter your userid: 1
Enter your name: Avi
Enter your salary: 30000
The gross salary of the Employee:  15501.0
Your id is:  1
Your name is:  Avi
Your usersalary is:  30000

In [4]:
car = {
"brand": "Ford",
"model": "Mustang",
"year": 1964
}

x = car.keys()

print(x) #before the change

car["color"] = "white"

print(x) #after the change

dict_keys(['brand', 'model', 'year'])
dict_keys(['brand', 'model', 'year', 'color'])

In [5]:
car = {
"brand": "Ford",
"model": "Mustang",
"year": 1964
}

x = car.values()

print(x) #before the change

car["year"] = 2020

print(x) #after the change

dict_values(['Ford', 'Mustang', 1964])
dict_values(['Ford', 'Mustang', 2020])